# Generated by Django 5.2.9 on 2026-01-03 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfsummary',
            old_name='pdf_file',
            new_name='pdf',
        ),
        migrations.RenameField(
            model_name='pdfsummary',
            old_name='summary_text',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='pdfsummary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
